# Generated by Django 4.0.4 on 2022-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
