# Generated by Django 4.0.4 on 2022-07-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_app', '0001_initial'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='Content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_content', to='mood_app.content'),
        ),
    ]
