<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-07-25 13:23
=======
# Generated by Django 4.0.4 on 2022-07-25 10:51
>>>>>>> e0dd2d2d3b194e22fc8b554cf257a71f3c73c36f

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('mood_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood_app', '0001_initial'),
>>>>>>> e0dd2d2d3b194e22fc8b554cf257a71f3c73c36f
    ]

    operations = [
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_mood', to='mood_app.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('pic', models.ImageField(null=True, upload_to='media/images/user_profile_pic')),
=======
                ('pic', models.ImageField(upload_to='media/images/user_profile_pic')),
>>>>>>> e0dd2d2d3b194e22fc8b554cf257a71f3c73c36f
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
